FROM golang:1.21.3

WORKDIR /tmp

ENV GO111MODULE=on GOBIN=/usr/local/bin

# buf
RUN go install github.com/bufbuild/buf/cmd/buf@v1.28.1

# grpc-web
ADD \
    --chmod='755' \
    https://github.com/grpc/grpc-web/releases/download/1.5.0/protoc-gen-grpc-web-1.5.0-linux-x86_64 \
    /usr/local/bin/protoc-gen-grpc-web

# protobuf-javascript
ADD \
    https://github.com/protocolbuffers/protobuf-javascript/releases/download/v3.21.2/protobuf-javascript-3.21.2-linux-x86_64.tar.gz \
    /tmp/protobuf-javascript.tar.gz
RUN tar -xvzf /tmp/protobuf-javascript.tar.gz -C /usr/local/bin/ --strip-components 1 bin/protoc-gen-js

WORKDIR /workspace
ENV HOME=/tmp
ENTRYPOINT [ "buf" ]
